### ISSUE TITLE
control over pip version

### ISSUE THREAD

**Issue by belm0** [sio/Makefile.venv#13] opened 2021-09-27 02:30 UTC
currently Makefile.venv tries to install the latest pip version at venv creation time

https://github.com/sio/Makefile.venv/blob/abfec932dc38833be2b5926994aca69f6d16a418/Makefile.venv#L136-L138

But we found that having an arbitrary version can cause problems.  The use case is when packaging wheel files so that we can have a local, "wheel-only" install (i.e. no indexes or network connection at install time).
  1. `pip wheel` is used, and the selected whl files are determined by the pip version
  2. at install time, a different pip version is used which doesn't support the packages wheel files
  
(for example, see the table at  https://github.com/pypa/manylinux)

So it may be useful to have an option to pin the pip version.

**Comment by sio** [comment] 2021-09-27 14:27
You have fairly specific requirements and, luckily, Makefile.venv can already accomodate them :)

[Here is](https://github.com/sio/bash-complete-partial-path/blob/2be6ef1f1885d3cb1ec2547ae41d78aa66f4ab78/Makefile#L42-L48) an example:

```makefile
# Override default venv packages for older Python versions
# https://github.com/pypa/get-pip/pull/46/files
ifeq (True,$(shell $(PY) -c "import sys; print(sys.version_info < (3,5))"))
$(VENV):
	$(PY) -m venv $(VENVDIR)
	$(VENV)/python -m pip install --upgrade "pip<19.2" "setuptools<44.0" "wheel<0.34"
endif
```

`ifeq`/`endif` are not necessary in your case, just provide a new recipe for venv creation after you `include Makefile.venv` 

It works because GNU Make [allows to redefine the recipe](https://www.gnu.org/software/make/manual/html_node/Multiple-Rules.html) for any target later in the Makefile. Downside is that this usage is not officially endorsed and GNU Make will spit out [some warnings](https://github.com/sio/bash-complete-partial-path/runs/3706546795?check_suite_focus=true#step:5:22):

```
Makefile:46: warning: overriding recipe for target '.venv/bin'
Makefile.venv:137: warning: ignoring old recipe for target '.venv/bin'
```

If you do not  want to hardcode the versions in your Makefile, you could do all sorts of stuff here:

```makefile
$(VENV):
	$(PY) -m venv $(VENVDIR)
	$(VENV)/python -m pip install -r path/to/your/file/with/requirements-for-pip-wheel-setuptools.txt
```

or

```makefile
CUSTOM_INITIAL_PACKAGES=path/to/your/file/with/requirements-for-pip-wheel-setuptools.txt
$(VENV):
	$(PY) -m venv $(VENVDIR)
	$(VENV)/python -m pip install -r $(CUSTOM_INITIAL_PACKAGES)
```

I like this solution because it allows for endless customization at practically zero cost. There is no way we could predict all oddly specific requests that users will come up with, let alone add variables and feature flags to support those. But with custom recipes users can define their venv whichever way they need. This is the [second time](https://github.com/sio/Makefile.venv/pull/10) this trick was sought after, so maybe I ought to add it to `docs/`

**Comment by sio** [comment] 2021-09-28 07:32
Thank you for finding this technique, I was not aware of it. I agree that current behavior is not perfect, but I'm inclined to keep things as they are until we find a solution that has less drawbacks.

I think shipping a wildcard `%` target with Makefile.venv is extremely invasive and violates the principle of least astonishement.

We are just a helper Makefile, not the main one. And authors of the main one may want to have the wildcard target for themselves. I think its wrong to be calling dibs here :-)

Another unexpected outcome of this would be mangling of error messages for non-existing recipes downstream. I imagine I'd be furious if a tool I use would turn a helpful error message into an unhelpful one.

Also, the StackOverflow example uses phony targets. Our $(VENV) is not phony, it's a directory. Adding a dependency from non-phony target to a phony one introduces some [hairy edge cases]. I'm not sure all of those can be mitigated by using [order-only prerequisites].

GNU Make is very stable software. I guess the whole Python venv ecosystem will be reinvented and will turn Makefile.venv obsolete sooner than GNU Make will drop support for the documented side effect a few of our users have come to rely on. So I think we're safe even if no perfect solution is ever to be found :-)

[hairy edge cases]: https://github.com/sio/Makefile.venv/actions/runs/1281525932
[order-only prerequisites]: https://github.com/sio/Makefile.venv/actions/runs/1281535467

**Comment by sio** [comment] 2021-10-01 11:23
I've added a [how-to article](https://github.com/sio/Makefile.venv/blob/master/docs/howto-custom-venv-recipe.md) describing the solution for this issue.

Since there were no follow-up comments from OP and I think the issue is solved, I'm closing this. Feel free to reopen if you have anything to add.

**Closed by sio** 2021-10-01 11:23 UTC
